name: Continuous integration Workflow

on:
  push:
    branches:
      - main

jobs:
  run_test:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/checkout@v4
        name: 'Checkout Repository'
      - name: 'Install Dependencies'
        run: npm install
      - name: 'Run Tests'
        env:
          credentials: ${{secrets.MONGODB_URI}}
        run: npm run test

  # Run the linter to check for code style issues
  lint:
    name: 'Run linter'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: 'Checkout repository'

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Run Linter'
        run: npx standard --fix